apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      version: blue
  template:
    metadata:
      labels:
        app: my-app
        version: blue
    spec:
      containers:
      - name: web
        image: europe-west4-docker.pkg.dev/project-sem-489814/app-repo/micro:main
        ports:
        - containerPort: 80
